# Generated by Django 4.2.7 on 2023-12-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='day_and_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='short_description',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='description', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='did_organizer_marking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(default='2023-12-15T09:39:43.826Z', verbose_name='Конец'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='num_places',
            field=models.PositiveSmallIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(default='2023-12-15T09:39:43.826Z', verbose_name='Начало'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='has_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.TextField(null=True, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='is_organizer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=6, null=True, verbose_name='Пол'),
        ),
    ]
