# Generated by Django 4.2.7 on 2023-12-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='users', to='api.category'),
        ),
    ]
