# Generated by Django 4.2.7 on 2023-11-29 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.theme'),
        ),
    ]
