# Generated by Django 4.2.7 on 2023-12-04 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_event_day_and_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventparticipant',
            name='is_registered',
        ),
    ]
