# Generated by Django 4.2.7 on 2023-12-05 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_date_of_birth_user_profile_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+7\\d{10}$')]),
        ),
    ]
