# Generated by Django 4.2.7 on 2023-11-30 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_category_theme'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventParticipants',
            new_name='EventParticipant',
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.profile')),
            ],
        ),
    ]
