# Generated by Django 4.2.7 on 2023-12-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_eventparticipants_eventparticipant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=6, verbose_name='Пол'),
        ),
    ]
