# Generated by Django 4.2.7 on 2023-12-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('rules', 'Правила'), ('agreement', 'Соглашение')], max_length=10, unique=True, verbose_name='Тип документа')),
                ('text', models.TextField()),
            ],
        ),
    ]
