# Generated by Django 4.2.7 on 2023-12-11 09:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.event', verbose_name='Событие'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='text',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.URLField(default='#', verbose_name='Ссылка'),
        ),
    ]
