# Generated by Django 4.2.7 on 2023-12-06 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_about_me_remove_user_interests_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('validity', models.IntegerField()),
                ('worth', models.TextField()),
                ('is_trial', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_expires',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.subscription'),
        ),
    ]
