# Generated by Django 4.2.7 on 2023-12-11 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_notification_created_at_notification_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_event', models.BooleanField()),
                ('text', models.TextField(max_length=500)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.event', verbose_name='Событие')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.supporttheme', verbose_name='Тема')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Профиль')),
            ],
        ),
    ]
