# Generated by Django 4.2.7 on 2023-12-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_supporttheme_supportmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportmessage',
            old_name='user',
            new_name='profile',
        ),
    ]
