# Generated by Django 4.2.7 on 2023-12-14 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_location_cover_location_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='last_time_viewed_chat',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to='api.event', verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL, verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to='api.supporttheme', verbose_name='Тема'),
        ),
    ]
