# Generated by Django 4.2.7 on 2023-12-15 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_eventparticipant_last_time_viewed_chat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='validity',
        ),
        migrations.AddField(
            model_name='subscription',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='worth',
            field=models.TextField(default=''),
        ),
    ]
