# Generated by Django 4.2.7 on 2023-12-15 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_subscription_validity_subscription_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventparticipant',
            name='last_time_viewed_chat',
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_expires',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
