# Generated by Django 4.2.7 on 2023-12-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_eventparticipant_last_time_viewed_chat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_expires',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
