# Generated by Django 4.2.7 on 2023-12-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_user_subscription_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_expires',
            field=models.DateTimeField(null=True),
        ),
    ]
