# Generated by Django 4.2.7 on 2023-12-18 15:13

import api.models.media
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_user_subscription_expires'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео')], verbose_name='Тип файла')),
                ('file', models.FileField(upload_to=api.models.media.get_upload_path)),
                ('file_name', models.CharField(verbose_name='Имя файла')),
                ('weight', models.FloatField()),
                ('duration', models.FloatField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='api.event')),
            ],
        ),
    ]
