# Generated by Django 4.2.7 on 2023-12-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_eventmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmedia',
            name='duration',
            field=models.FloatField(null=True),
        ),
    ]
