# Generated by Django 4.2.7 on 2023-12-20 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_user_options_user_agreement_applied_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
