# Generated by Django 4.2.7 on 2023-12-20 10:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about_me',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Обо мне'),
        ),
        migrations.AlterField(
            model_name='user',
            name='agreement_applied_at',
            field=models.DateTimeField(null=True, verbose_name='Дата принятия соглашения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Почта подтверждена'),
        ),
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(related_name='users', to='api.category', verbose_name='Интересы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.occupation', verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+7\\d{10}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.subscription', verbose_name='Подписка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_expires',
            field=models.DateTimeField(null=True, verbose_name='Дата окончания подписки'),
        ),
    ]
