# Generated by Django 4.2.7 on 2023-12-21 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_country_options_alter_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date'], 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='eventparticipant',
            options={'verbose_name': 'Участник события', 'verbose_name_plural': 'Участники события'},
        ),
    ]
