# Generated by Django 4.2.7 on 2023-12-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_eventmedia_author_alter_eventmedia_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активное'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_is_completed',
            field=models.BooleanField(default=False, verbose_name='Профиль заполнен'),
        ),
    ]
