# Generated by Django 4.2.7 on 2023-12-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_supportrequesttheme_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequesttheme',
            name='name',
            field=models.CharField(max_length=31, unique=True, verbose_name='Название темы'),
        ),
    ]
