# Generated by Django 4.2.7 on 2023-12-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sending_push',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
