# Generated by Django 4.2.7 on 2023-12-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_event_cover_alter_location_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFastFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('today', 'Сегодня'), ('tomorrow', 'Завтра'), ('my_city', 'Мой город')], max_length=8, unique=True)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
