# Generated by Django 4.2.7 on 2023-12-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_eventfastfilter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventfastfilter',
            options={'verbose_name': 'Быстрый фильтр', 'verbose_name_plural': 'Быстрые фильтры'},
        ),
        migrations.AlterField(
            model_name='eventfastfilter',
            name='is_active',
            field=models.BooleanField(verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='eventfastfilter',
            name='name',
            field=models.CharField(choices=[('today', 'Сегодня'), ('tomorrow', 'Завтра'), ('my_city', 'Мой город')], max_length=8, unique=True, verbose_name='Имя'),
        ),
    ]
