# Generated by Django 4.2.7 on 2023-12-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_eventfastfilter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmedia',
            name='duration',
            field=models.FloatField(blank=True, null=True, verbose_name='Длительность'),
        ),
    ]
