# Generated by Django 4.2.7 on 2023-12-28 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_event_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docs',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterField(
            model_name='event',
            name='max_age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(100)], verbose_name='Макс. возраст'),
        ),
        migrations.AlterField(
            model_name='event',
            name='min_age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(99)], verbose_name='Мин. возраст'),
        ),
    ]
