# Generated by Django 4.2.7 on 2024-01-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_user_receive_recs_alter_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
