# Generated by Django 4.2.7 on 2024-01-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_remove_supportrequestmessage_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequestmessage',
            name='type',
            field=models.CharField(choices=[('complaint', 'Жалоба'), ('help', 'Помощь')], verbose_name='Тип обращения'),
        ),
    ]
