# Generated by Django 4.2.7 on 2024-01-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_supportrequestmessage_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportrequestmessage',
            name='type',
        ),
        migrations.AddField(
            model_name='supportrequesttheme',
            name='type',
            field=models.CharField(choices=[('complaint', 'Жалоба'), ('help', 'Помощь')], default='complaint', verbose_name='Тип обращения'),
            preserve_default=False,
        ),
    ]
