# Generated by Django 4.2.7 on 2024-01-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_remove_supportrequestmessage_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequestmessage',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Текст'),
        ),
    ]
