# Generated by Django 4.2.7 on 2024-01-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_supportrequestmessage_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='is_organizer',
            field=models.BooleanField(default=False),
        ),
    ]
