# Generated by Django 4.2.7 on 2024-01-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_remove_event_organizer_eventparticipant_is_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='event_rules_applied',
            field=models.BooleanField(default=False),
        ),
    ]
