# Generated by Django 4.2.7 on 2024-02-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_remove_user_interests_user_categories_user_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='chat_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
