# Generated by Django 4.2.7 on 2024-02-07 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_eventparticipant_chat_notifications'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventparticipant',
            unique_together={('event', 'user')},
        ),
    ]
