# Generated by Django 4.2.7 on 2024-02-08 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_user_date_of_birth_alter_user_email_and_more'),
        ('api', '0051_alter_event_cover_alter_location_cover_and_more'),
        ('api', '0051_alter_eventparticipant_unique_together'),
    ]

    operations = [
    ]
