# Generated by Django 4.2.7 on 2024-02-21 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_user_categories'),
        ('api', '0052_merge_20240208_1756'),
    ]

    operations = [
    ]
