# Generated by Django 4.2.7 on 2024-02-29 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_merge_20240229_1439'),
        ('api', '0055_user_offer_applied_alter_docs_name'),
    ]

    operations = [
    ]
