# Generated by Django 4.2.7 on 2024-03-05 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_user_offer_applied_alter_docs_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmedia',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='eventmedia',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='eventmedia',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='eventmedia',
            name='weight',
        ),
    ]
