# Generated by Django 4.2.7 on 2024-03-06 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_merge_20240229_1732'),
        ('api', '0056_remove_eventmedia_duration_and_more'),
    ]

    operations = [
    ]
