# Generated by Django 4.2.7 on 2024-03-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_alter_eventmedia_mimetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmedia',
            name='preview',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
