# Generated by Django 4.2.7 on 2024-03-07 13:58

import api.models.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_alter_eventmedia_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmedia',
            name='file',
            field=models.FileField(max_length=511, upload_to=api.models.media.get_upload_path, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='eventmedia',
            name='preview',
            field=models.FileField(blank=True, max_length=511, null=True, upload_to=''),
        ),
    ]
