# Generated by Django 4.2.7 on 2024-03-07 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_alter_eventmedia_file_alter_eventmedia_preview'),
        ('api', '0060_merge_20240307_1400'),
    ]

    operations = [
    ]
