# Generated by Django 4.2.7 on 2024-07-30 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_eventparticipant_kicked_by_organizer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
    ]
