# Generated by Django 5.1 on 2024-08-12 10:21

import uuid
from django.db import migrations, models


def forwards(apps, _):
    User = apps.get_model("api", "User")
    for user in User.objects.iterator():
        user.uuid = uuid.uuid4()
        user.save()


def backwards(apps, _):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0065_event_organizer_will_pay_eventparticipant_payed"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.RunPython(forwards, backwards),
    ]
