# Generated by Django 5.1 on 2025-01-22 16:12

import django.contrib.admin.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def forwards(apps, _):
    LogEntry = apps.get_model("admin", "LogEntry")
    HistoryLog = apps.get_model("admin_history", "HistoryLog")

    HistoryLog.objects.bulk_create(
        [
            HistoryLog(
                **{
                    field: getattr(log_entry, field)
                    for field in (
                        "action_time",
                        "user_id",
                        "content_type_id",
                        "object_id",
                        "object_repr",
                        "action_flag",
                        "change_message",
                    )
                }
            )
            for log_entry in LogEntry.objects.iterator()
        ]
    )


def backwards(apps, _):
    pass


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("admin", "0003_logentry_add_action_flag_choices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="action time",
                    ),
                ),
                (
                    "object_id",
                    models.TextField(blank=True, null=True, verbose_name="object id"),
                ),
                (
                    "object_repr",
                    models.CharField(max_length=200, verbose_name="object repr"),
                ),
                (
                    "action_flag",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Addition"), (2, "Change"), (3, "Deletion")],
                        verbose_name="action flag",
                    ),
                ),
                (
                    "change_message",
                    models.TextField(blank=True, verbose_name="change message"),
                ),
                ("is_admin", models.BooleanField(default=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "log entry",
                "verbose_name_plural": "log entries",
                "ordering": ["-action_time"],
            },
            managers=[
                ("objects", django.contrib.admin.models.LogEntryManager()),
            ],
        ),
        migrations.RunPython(forwards, backwards),
    ]
