# Generated by Django 5.1 on 2025-01-23 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_history', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historylog',
            name='read_users',
            field=models.ManyToManyField(blank=True, related_name='read_history_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
