# Generated by Django 5.1 on 2025-01-23 15:59

import apps.admin_history.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_history', '0002_historylog_read_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='historylog',
            managers=[
                ('objects', apps.admin_history.models.HistoryLogManager()),
            ],
        ),
        migrations.AlterField(
            model_name='historylog',
            name='action_flag',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Addition'), (2, 'Change'), (3, 'Deletion'), (4, 'Другое')], verbose_name='action flag'),
        ),
        migrations.AlterField(
            model_name='historylog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
