# Generated by Django 5.1 on 2025-02-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_history', '0003_alter_historylog_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historylog',
            name='object_data',
            field=models.JSONField(default=dict),
        ),
    ]
