# Generated by Django 5.1 on 2024-08-12 10:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TinkoffTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('coins', 'Монеты'), ('subscription', 'Подписка')], max_length=16, verbose_name='Тип продукта')),
                ('product_id', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField(default=0, help_text='Оплачиваемая сумма в рублях', verbose_name='Сумма к оплате')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID платежа')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tinkoff payment ID')),
                ('payment_url', models.URLField(blank=True, null=True, verbose_name='Tinkoff payment url')),
                ('status', models.CharField(choices=[('PENDING', 'В ожидании'), ('MONEY_HOLD', 'Деньги заморожены'), ('SUCCESS', 'Успешно'), ('FAILED', 'Неудачно'), ('CANCELED', 'Отменено')], default='PENDING', max_length=15, verbose_name='Статус оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
    ]
