# Generated by Django 5.1 on 2025-07-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_tinkofftransaction_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpayment',
            name='payer',
        ),
        migrations.AddField(
            model_name='eventpayment',
            name='payment_type',
            field=models.CharField(choices=[('organization', 'Организация мероприятия'), ('participance', 'Участие в мероприятии')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tinkofftransaction',
            name='payment_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
