# Generated by Django 5.1 on 2025-07-22 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_eventpayment_payer_eventpayment_payment_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tinkofftransaction',
            old_name='payment_type',
            new_name='product_name',
        ),
    ]
