# Generated by Django 5.1 on 2025-07-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_payment_type_tinkofftransaction_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinkofftransaction',
            name='product_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
