# Generated by Django 5.1 on 2025-07-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_tinkofftransaction_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tinkofftransaction',
            name='product_name',
        ),
        migrations.AddField(
            model_name='tinkofftransaction',
            name='product_type',
            field=models.CharField(choices=[('organization', 'Организация мероприятия'), ('participance', 'Участие в мероприятии')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='EventPayment',
        ),
    ]
