# Generated by Django 5.1 on 2025-07-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_remove_tinkofftransaction_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgPaymentProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты организаторов',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payment.tinkofftransaction',),
        ),
        migrations.CreateModel(
            name='PartPaymentProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты присоединившихся',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payment.tinkofftransaction',),
        ),
    ]
