# Generated by Django 5.1 on 2025-07-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_paymentinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinkofftransaction',
            name='deal_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Split deal ID'),
        ),
    ]
