# Generated by Django 5.1 on 2025-08-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_tinkofftransaction_deal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinkofftransaction',
            name='ticket_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер билета'),
        ),
    ]
