# Generated by Django 5.1 on 2025-08-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_tinkofftransaction_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinkofftransaction',
            name='service_reward',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Вознаграждение сервиса'),
        ),
        migrations.AddField(
            model_name='tinkofftransaction',
            name='transaction_type',
            field=models.CharField(choices=[('payment', 'Основной платёж'), ('transfer', 'Перевод')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tinkofftransaction',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Оплачиваемая сумма в рублях', max_digits=15, verbose_name='Сумма к оплате'),
        ),
    ]
