# Generated by Django 5.1 on 2025-09-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_tinkofftransaction_service_reward_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrgPaymentProxy',
        ),
        migrations.DeleteModel(
            name='PartPaymentProxy',
        ),
        migrations.RemoveField(
            model_name='tinkofftransaction',
            name='deal_id',
        ),
        migrations.RemoveField(
            model_name='tinkofftransaction',
            name='event',
        ),
        migrations.RemoveField(
            model_name='tinkofftransaction',
            name='service_reward',
        ),
        migrations.RemoveField(
            model_name='tinkofftransaction',
            name='ticket_id',
        ),
        migrations.RemoveField(
            model_name='tinkofftransaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='tinkofftransaction',
            name='product_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tinkofftransaction',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Оплачиваемая сумма в рублях', verbose_name='Сумма к оплате'),
        ),
        migrations.AlterField(
            model_name='tinkofftransaction',
            name='product_type',
            field=models.CharField(blank=True, choices=[('coins', 'Монеты'), ('subscription', 'Подписка')], max_length=16, null=True, verbose_name='Тип продукта'),
        ),
        migrations.DeleteModel(
            name='PaymentInfo',
        ),
    ]
