# Generated by Django 4.2.7 on 2024-03-05 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='title',
            field=models.CharField(default='tmp', max_length=50, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('event_join', 'Вступление в событие'), ('EVENT_REMIND', 'Напоминание о событии'), ('EVENT_CANCELED', 'Событие отменено'), ('EVENT_CHANGED', 'Событие изменено'), ('EVENT_REC', 'Рекомендованное событие'), ('ADMIN', 'От администрации')], verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivers', to='notifications.notification', verbose_name='Уведомление'),
        ),
    ]
