# Generated by Django 4.2.7 on 2024-03-05 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_usernotification_title_alter_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('EVENT_REMIND', 'Напоминание о событии'), ('EVENT_CANCELED', 'Событие отменено'), ('EVENT_CHANGED', 'Событие изменено'), ('EVENT_REC', 'Рекомендованное событие'), ('ADMIN', 'От администрации')], verbose_name='Тип'),
        ),
    ]
