# Generated by Django 4.2.7 on 2024-03-15 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_alter_eventmedia_file_alter_eventmedia_preview'),
        ('notifications', '0006_usernotification_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EVENT_REMIND', 'Напоминание о событии'), ('EVENT_CANCELED', 'Событие отменено'), ('EVENT_CHANGED', 'Событие изменено'), ('EVENT_REC', 'Рекомендованное событие'), ('ADMIN', 'От администрации')], verbose_name='Тип')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Заголовок')),
                ('body', models.TextField(max_length=500, null=True, verbose_name='Текст')),
                ('task_id', models.CharField(max_length=255, null=True, verbose_name='ID задачи')),
                ('remind_hours', models.PositiveSmallIntegerField(null=True, verbose_name='Кол-во часов до начала')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.event', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receivers', to='notifications.groupnotification', verbose_name='Уведомление'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
