# Generated by Django 4.2.7 on 2024-03-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_groupnotification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupnotification',
            name='remind_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Кол-во часов до начала'),
        ),
        migrations.AlterField(
            model_name='groupnotification',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID задачи'),
        ),
    ]
