version: "3"

services:
  backend:
    container_name: vmeste_backend
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile.dev
    entrypoint: ./docker/backend/entrypoint.dev.sh
    restart: always
    volumes:
      - .:/app
      - ./backend/static/:/app/backend/static/
      - ./backend/media/:/app/backend/media/
      - /var/certbot/conf:/etc/letsencrypt/:ro
    expose:
      - 8000
    env_file:
      - ./docker/backend/dev.env
    depends_on:
      - db
      - elasticsearch
    networks:
      - vmeste_back_default

  db:
    container_name: vmeste_db
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./backend/static/:/app/backend/static/
      - ./backend/media/:/app/backend/media/
    env_file:
      - ./docker/backend/dev.env
    ports:
      - 5432:5432
    networks:
      - vmeste_back_default

  nginx:
    container_name: vmeste_nginx
    build: ./docker/nginx
    volumes:
      - ./docker/nginx/conf/:/etc/nginx/conf.d/
      - ./backend/static/:/app/backend/static/
      - ./backend/media/:/app/backend/media/
    ports:
      - 8000:80
    restart: always
    depends_on:
      - backend
    networks:
      - vmeste_back_default

  celery:
    container_name: vmeste_celery
    restart: always
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile.dev
    volumes:
      - .:/app
    env_file:
      - ./docker/backend/dev.env
    entrypoint: ./docker/backend/celery-entrypoint.sh
    depends_on:
      - backend
      - db
      - rabbit
    networks:
      - vmeste_back_default

  rabbit:
    container_name: vmeste_rabbit
    restart: always
    image: rabbitmq:3.10-management
    hostname: rabbitmq
    expose:
      - 5672
      - 15672
    env_file:
      - ./docker/backend/dev.env
    volumes:
      - .:/app
      - rabbitmqdata:/var/lib/rabbitmq
    networks:
      - vmeste_back_default

  elasticsearch:
    container_name: vmeste_elasticsearch
    image: elasticsearch:8.11.1
    restart: always
    volumes:
      - elsdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    networks:
      - vmeste_back_default

  redis:
    image: redis:7.0.10-alpine
    restart: always
    container_name: vmeste_redis
    expose:
      - 6379
    networks:
      - vmeste_back_default

volumes:
  rabbitmqdata:
  elsdata:

networks:
  vmeste_back_default:
