version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile.dev
    entrypoint: ./docker/backend/entrypoint.dev.sh
    restart: always
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./docker/backend/dev.env
    depends_on:
      - db
  
  db:
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./docker/backend/dev.env
    ports:
      - 5432:5432