services:
  backend:
    container_name: vmeste_backend
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile.dev
    entrypoint: ./docker/backend/entrypoint.dev.sh
    restart: always
    volumes:
      - .:/app
      - static:/app/backend/static/
      - media:/app/backend/media/
      - /var/certbot/conf:/etc/letsencrypt/:ro
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - vmeste_back_default
    logging:
      driver: "json-file"
      options:
        max-size: "5gb"

  db:
    container_name: vmeste_db
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - vmeste_back_default
    logging:
      driver: "json-file"
      options:
        max-size: "5gb"

  nginx:
    container_name: vmeste_nginx
    image: nginx:latest
    volumes:
      - ./docker/nginx/conf/:/etc/nginx/conf.d/
      - certbot_www:/var/www/certbot/:ro
      - certbot_conf:/etc/nginx/ssl/:ro
      - static:/app/backend/static/
      - media:/app/backend/media/
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - backend
    networks:
      - vmeste_back_default
    logging:
      driver: "json-file"
      options:
        max-size: "5gb"

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot_www:/var/www/certbot/:rw
      - certbot_conf:/etc/letsencrypt/:rw
    depends_on:
      - nginx
    networks:
      - vmeste_back_default
    logging:
      driver: "json-file"
      options:
        max-size: "5gb"

  celery:
    container_name: vmeste_celery
    restart: always
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile.dev
    volumes:
      - .:/app
    env_file:
      - .env
    entrypoint: ./docker/backend/celery-entrypoint.sh
    depends_on:
      - backend
      - db
      - rabbit
    networks:
      - vmeste_back_default
    logging:
      driver: "json-file"
      options:
        max-size: "5gb"

  rabbit:
    container_name: vmeste_rabbit
    restart: always
    image: rabbitmq:3.10-management
    hostname: rabbitmq
    expose:
      - 5672
      - 15672
    env_file:
      - .env
    volumes:
      - .:/app
      - rabbitmqdata:/var/lib/rabbitmq
    networks:
      - vmeste_back_default
    logging:
      driver: "json-file"
      options:
        max-size: "5gb"

  elasticsearch:
    container_name: vmeste_elasticsearch
    image: elasticsearch:7.17.9
    restart: always
    volumes:
      - elsdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ingest.geoip.downloader.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200:9200
    networks:
      - vmeste_back_default
    logging:
      driver: "json-file"
      options:
        max-size: "5gb"

  redis:
    image: redis:7.0.10-alpine
    restart: always
    container_name: vmeste_redis
    expose:
      - 6379
    networks:
      - vmeste_back_default
    logging:
      driver: "json-file"
      options:
        max-size: "5gb"

volumes:
  rabbitmqdata:
  elsdata:
  pgdata:
  static:
  media:
  certbot_www:
  certbot_conf:

networks:
  vmeste_back_default:
