# Generated by Django 4.2.7 on 2024-03-05 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_user_offer_applied_alter_docs_name'),
        ('notifications', '0005_usernotification_created_at_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='api.event', verbose_name='Событие'),
        ),
    ]
