# Generated by Django 4.2.7 on 2024-03-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_groupnotification_remind_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='body',
            field=models.TextField(max_length=500, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовок'),
        ),
    ]
