# Generated by Django 5.1 on 2024-11-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_usernotification_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupnotification',
            name='type',
            field=models.CharField(choices=[('EVENT_REMIND', 'Напоминание о событии'), ('EVENT_CANCELED', 'Событие отменено'), ('EVENT_CHANGED', 'Событие изменено'), ('EVENT_ADDED', 'Новое событие'), ('EVENT_REC', 'Рекомендованное событие'), ('ADMIN', 'От администрации')], verbose_name='Тип'),
        ),
    ]
