# Generated by Django 5.1 on 2024-12-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_alter_groupnotification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupnotification',
            name='related_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupnotification',
            name='type',
            field=models.CharField(choices=[('EVENT_REMIND', 'Напоминание о событии'), ('EVENT_CANCELED', 'Событие отменено'), ('EVENT_CHANGED', 'Событие изменено'), ('EVENT_ADDED', 'Новое событие'), ('EVENT_REC', 'Рекомендованное событие'), ('ADMIN', 'От администрации'), ('CHAT_JOIN', 'Пользователь присоединился к чату')], verbose_name='Тип'),
        ),
    ]
