# Generated by Django 5.1 on 2025-01-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_groupnotification_related_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupnotification',
            name='type',
            field=models.CharField(choices=[('EVENT_REMIND', 'Напоминание о событии'), ('EVENT_CANCELED', 'Событие отменено'), ('EVENT_REJECT', 'Пользователь отписался от события'), ('EVENT_CHANGED', 'Событие изменено'), ('EVENT_ADDED', 'Новое событие'), ('EVENT_REC', 'Рекомендованное событие'), ('ADMIN', 'От администрации'), ('CHAT_JOIN', 'Пользователь присоединился к чату')], verbose_name='Тип'),
        ),
    ]
