# Generated by Django 5.1 on 2025-02-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_alter_groupnotification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки'),
        ),
    ]
