# Generated by Django 4.2.7 on 2023-12-15 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_message_read_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read_by',
        ),
        migrations.CreateModel(
            name='ReadMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read', to='chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
