# Generated by Django 4.2.7 on 2024-01-12 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_location_latitude_alter_location_longitude'),
        ('chat', '0005_alter_message_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='id',
        ),
        migrations.AlterField(
            model_name='chat',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='chat', serialize=False, to='api.event', verbose_name='Событие'),
        ),
    ]
