# Generated by Django 4.2.7 on 2024-01-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_chat_id_alter_chat_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=300, verbose_name='Текст'),
        ),
    ]
