# Generated by Django 4.2.7 on 2024-02-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_message_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_info',
            field=models.BooleanField(default=False),
        ),
    ]
