# Generated by Django 4.2.7 on 2024-02-07 08:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_alter_message_text'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='readmessage',
            unique_together={('message', 'user')},
        ),
    ]
