# Generated by Django 4.2.7 on 2024-02-20 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_message_is_info'),
        ('chat', '0008_alter_readmessage_unique_together'),
    ]

    operations = [
    ]
