# Generated by Django 4.2.7 on 2024-02-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_message_options'),
        ('chat', '0009_merge_20240220_1334'),
    ]

    operations = [
    ]
