# Generated by Django 5.1 on 2025-02-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_merge_20240228_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_info',
            field=models.BooleanField(default=False, verbose_name='Информационное'),
        ),
    ]
