# Generated by Django 4.2.7 on 2023-12-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_user_supportmessage_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='cover',
            field=models.TextField(default='base64', verbose_name='Обложка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Скидка'),
        ),
    ]
