# Generated by Django 4.2.7 on 2023-12-21 08:42

import apps.api.models.user
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_alter_user_about_me_alter_user_agreement_applied_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name": "Страна", "verbose_name_plural": "Страны"},
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.api.models.user.get_upload_path,
                verbose_name="Аватар",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="confirmation_code",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Почта"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, null=True, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Мужской"), ("female", "Женский")],
                max_length=6,
                null=True,
                verbose_name="Пол",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, null=True, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="user",
            name="subscription_expires",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата окончания подписки"
            ),
        ),
    ]
