# Generated by Django 4.2.7 on 2023-12-21 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_event_is_active_alter_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmedia',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='media', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
