# Generated by Django 4.2.7 on 2023-12-21 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0025_eventmedia_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventmedia",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="eventmedia",
            name="duration",
            field=models.FloatField(null=True, verbose_name="Длительность"),
        ),
        migrations.AlterField(
            model_name="eventmedia",
            name="file",
            field=models.FileField(
                upload_to=apps.api.models.media.get_upload_path, verbose_name="Файл"
            ),
        ),
        migrations.AlterField(
            model_name="eventmedia",
            name="file_name",
            field=models.CharField(verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="eventmedia",
            name="file_type",
            field=models.CharField(
                choices=[("photo", "Фото"), ("video", "Видео")], verbose_name="Тип"
            ),
        ),
        migrations.AlterField(
            model_name="eventmedia",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата загрузки"),
        ),
        migrations.AlterField(
            model_name="eventmedia",
            name="weight",
            field=models.FloatField(verbose_name="Вес (Кб)"),
        ),
    ]
