# Generated by Django 4.2.7 on 2023-12-25 14:21

from django.db import migrations, models

import apps.api.models.event
import apps.api.models.location


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0032_user_sending_push_delete_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="cover",
            field=models.ImageField(
                upload_to=apps.api.models.event.get_upload_path, verbose_name="Обложка"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="cover",
            field=models.ImageField(
                upload_to=apps.api.models.location.get_upload_path,
                verbose_name="Обложка",
            ),
        ),
    ]
