# Generated by Django 4.2.7 on 2023-12-27 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_eventmedia_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='link',
        ),
    ]
