# Generated by Django 4.2.7 on 2024-01-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_event_end_datetime_alter_event_start_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportrequestmessage',
            name='subject',
        ),
        migrations.AddField(
            model_name='supportrequestmessage',
            name='type',
            field=models.CharField(choices=[('complaint', 'Жалоба'), ('help', 'Помощь')], default='complaint', verbose_name='Тип объекта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supportrequestmessage',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('in_process', 'На рассмотрении'), ('reviewed', 'Рассмотрено')], default='new', verbose_name='Статус'),
        ),
    ]
