# Generated by Django 4.2.7 on 2024-02-08 14:33

import apps.api.models.location
import apps.api.models.user
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0050_eventparticipant_chat_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="cover",
            field=models.ImageField(
                default="defaults/cover.jpg",
                upload_to=apps.api.models.event.get_upload_path,
                verbose_name="Обложка",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="cover",
            field=models.ImageField(
                default="defaults/cover.jpg",
                upload_to=apps.api.models.location.get_upload_path,
                verbose_name="Обложка",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="defaults/avatar.png",
                upload_to=apps.api.models.user.get_upload_path,
                verbose_name="Аватар",
            ),
        ),
    ]
