# Generated by Django 4.2.7 on 2024-02-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_event_cover_alter_location_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='users', to='api.category', verbose_name='Категории'),
        ),
    ]
