# Generated by Django 4.2.7 on 2024-02-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_alter_event_description_and_more'),
        ('api', '0053_merge_20240221_1234'),
    ]

    operations = [
    ]
