# Generated by Django 4.2.7 on 2024-02-29 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_alter_event_description_and_more'),
        ('api', '0054_merge_20240228_1929'),
    ]

    operations = [
    ]
