# Generated by Django 4.2.7 on 2024-02-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='offer_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='docs',
            name='name',
            field=models.CharField(choices=[('rules', 'Правила'), ('agreement', 'Соглашение'), ('offer', 'Оферта')], max_length=10, unique=True, verbose_name='Тип документа'),
        ),
    ]
