# Generated by Django 4.2.7 on 2024-03-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_remove_eventmedia_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmedia',
            name='mimetype',
            field=models.CharField(default='photo/jpeg', max_length=31),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventmedia',
            name='preview',
            field=models.FileField(blank=True, null=True, upload_to='previews/'),
        ),
    ]
