# Generated by Django 4.2.7 on 2024-03-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_eventmedia_mimetype_eventmedia_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmedia',
            name='mimetype',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
    ]
