# Generated by Django 4.2.7 on 2024-03-07 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_merge_20240306_0850'),
        ('api', '0059_alter_eventmedia_preview'),
    ]

    operations = [
    ]
