# Generated by Django 4.2.7 on 2024-03-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_merge_20240307_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='kicked_by_organizer',
            field=models.BooleanField(default=False),
        ),
    ]
