# Generated by Django 4.2.7 on 2024-07-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_alter_city_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='organizer_price',
            field=models.PositiveIntegerField(default=5, verbose_name='Стоимость для организаторов'),
        ),
        migrations.AddField(
            model_name='theme',
            name='participant_price',
            field=models.PositiveIntegerField(default=1, verbose_name='Стоимость для участников'),
        ),
    ]
