# Generated by Django 4.2.7 on 2024-08-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_theme_organizer_price_theme_participant_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer_will_pay',
            field=models.BooleanField(default=True, verbose_name='Организатор оплатит встречу'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='payed',
            field=models.PositiveIntegerField(default=0, verbose_name='Оплачено'),
        ),
    ]
