# Generated by Django 5.1 on 2024-12-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer_will_pay',
            field=models.BooleanField(blank=True, null=True, verbose_name='Организатор оплатит встречу'),
        ),
    ]
