# Generated by Django 5.1 on 2024-12-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_alter_event_organizer_will_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='total_female',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Всего женщин'),
        ),
        migrations.AlterField(
            model_name='event',
            name='total_male',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Всего мужчин'),
        ),
    ]
