# Generated by Django 5.1 on 2024-12-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_user_is_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
