# Generated by Django 5.1 on 2024-12-24 09:38

import apps.api.models.event
import core.model_fields.compresed_image
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0070_alter_user_is_registered"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="cover_medium",
            field=core.model_fields.compresed_image.CompressedImageField(
                default="defaults/cover.jpg",
                upload_to=apps.api.models.event.get_upload_path_medium,
                verbose_name="Обложка",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="cover",
            field=core.model_fields.compresed_image.CompressedImageField(
                default="defaults/cover.jpg",
                upload_to=apps.api.models.event.get_upload_path,
                verbose_name="Обложка",
            ),
        ),
    ]
