# Generated by Django 5.1 on 2024-12-24 10:47

import apps.api.models.user
import core.model_fields.compresed_image
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_event_cover_medium_alter_event_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=core.model_fields.compresed_image.CompressedImageField(default='defaults/avatar.png', upload_to=apps.api.models.user.get_upload_path, verbose_name='Аватар'),
        ),
    ]
