# Generated by Django 5.1 on 2025-01-22 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('sent', models.BooleanField(default=False, verbose_name='Отправлен')),
                ('support', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='api.supportrequestmessage')),
            ],
            options={
                'verbose_name': 'Ответ на обращение',
                'verbose_name_plural': 'Ответы на обращения',
            },
        ),
    ]
