# Generated by Django 5.1 on 2025-01-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_supportanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'Старт событий',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.event',),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала'),
        ),
    ]
