# Generated by Django 5.1 on 2025-01-22 11:30

import apps.api.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_eventadminproxy_alter_event_start_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedUser',
            fields=[
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Удалённые пользователи',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.user',),
            managers=[
                ('objects', apps.api.models.user.DeletedUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
