# Generated by Django 5.1 on 2025-01-22 16:12

import apps.api.models.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_deleteduser_user_is_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.api.models.user.UserManager()),
                ('all_objects', apps.api.models.user.AllUserManager()),
            ],
        ),
    ]
