# Generated by Django 5.1 on 2025-01-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='total_people',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Всего участников'),
        ),
    ]
