# Generated by Django 5.1 on 2025-02-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_location_user_alter_location_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
