# Generated by Django 5.1 on 2025-02-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_alter_docs_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Код подтверждения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='event_rules_applied',
            field=models.BooleanField(default=False, verbose_name='Правила сервиса'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_registered',
            field=models.BooleanField(default=False, verbose_name='Зарегистрирован'),
        ),
        migrations.AlterField(
            model_name='user',
            name='offer_applied',
            field=models.BooleanField(default=False, verbose_name='Оферта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='receive_recs',
            field=models.BooleanField(default=True, verbose_name='Рекомендовать события'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sending_push',
            field=models.BooleanField(default=True, verbose_name='Отправка уведомлений'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телеграм'),
        ),
    ]
