# Generated by Django 5.1 on 2025-06-09 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_alter_user_confirmation_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='organizer_price',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='participant_price',
        ),
        migrations.AddField(
            model_name='theme',
            name='commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Комиссия сервиса'),
        ),
        migrations.AddField(
            model_name='theme',
            name='payment_type',
            field=models.CharField(choices=[('FREE', 'Бесплатные'), ('MASTER', 'Платные, платит организатор'), ('PROF', 'Платные, платят участники')], default='FREE', verbose_name='Тип оплаты'),
        ),
        migrations.AddField(
            model_name='theme',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость'),
        ),
    ]
