# Generated by Django 5.1 on 2025-07-17 16:31

# import apps.api.validators
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_remove_theme_organizer_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer_will_pay',
        ),
        migrations.AddField(
            model_name='event',
            name='sign_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Плата за вступление'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('FREE', 'Free'), ('MASTER', 'Master'), ('PRO', 'Profi')], default='FREE', max_length=8, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='payment_type',
            field=models.CharField(choices=[('FREE', 'Бесплатные'), ('MASTER', 'Платные, платит организатор'), ('PROF', 'Платные, платят участники')], default='FREE', max_length=16, verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Стоимость'),
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256, verbose_name='Название компании')),
                ('legal_address', models.TextField(verbose_name='Юридический адрес')),
                ('full_name', models.CharField(verbose_name='ФИО ответственного')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона ответственного')),
                ('director_full_name', models.CharField(verbose_name='ФИО директора')),
                ('director_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона директора')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('ogrn', models.CharField(max_length=13, verbose_name='ОГРН')),
                ('bic', models.CharField(max_length=9, verbose_name='БИК банка')),
                ('bank_name', models.CharField(max_length=256, verbose_name='Название банка')),
                ('current_account', models.CharField(max_length=20, verbose_name='Номер расчетного счета в рублях')),
                ('sites', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=list, size=None)),
                ('confirmed', models.BooleanField(default=False, verbose_name='Подтверждён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_entity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Карточка юр. лица',
                'verbose_name_plural': 'Карточки юр. лица',
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(upload_to='', verbose_name='Файл документа')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Подтверждён')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Верификация',
                'verbose_name_plural': 'Верификация',
            },
        ),
    ]
