# Generated by Django 5.1 on 2025-07-22 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_remove_event_organizer_will_pay_event_sign_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='theme',
        ),
    ]
