# Generated by Django 5.1 on 2025-07-22 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_remove_category_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='theme',
        ),
    ]
