# Generated by Django 5.1 on 2025-07-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_remove_user_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='paid_by_organizer',
            field=models.BooleanField(default=False),
        ),
    ]
