# Generated by Django 5.1 on 2025-07-23 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_event_paid_by_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
