# Generated by Django 5.1 on 2025-07-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_remove_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('FREE', 'Free'), ('MASTER', 'Master'), ('PROFI', 'Profi')], default='FREE', max_length=8, verbose_name='Статус'),
        ),
    ]
