# Generated by Django 5.1 on 2025-07-23 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.theme', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
