# Generated by Django 5.1 on 2025-07-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_category_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legalentity',
            old_name='full_name',
            new_name='resp_full_name',
        ),
    ]
