# Generated by Django 5.1 on 2025-07-23 14:24

# import apps.api.models.legal_entity
import core.model_fields.compresed_image
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_rename_full_name_legalentity_resp_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legalentity',
            old_name='phone_number',
            new_name='resp_phone_number',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='director_phone_number',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='ogrn',
        ),
        migrations.AddField(
            model_name='legalentity',
            name='image',
            field=core.model_fields.compresed_image.CompressedImageField(blank=True, null=True, upload_to="", verbose_name='Картинка'),
        ),
    ]
