# Generated by Django 5.1 on 2025-07-25 11:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_rename_phone_number_legalentity_resp_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='sites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, null=True, size=None),
        ),
    ]
