# Generated by Django 5.1 on 2025-08-05 10:32

# import apps.api.models.participant
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_alter_legalentity_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='scanner_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_to_scan', to=settings.AUTH_USER_MODEL, verbose_name='Проверяющий сотрудник'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to="", verbose_name='QR-код'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='qr_code_verified',
            field=models.BooleanField(default=False, verbose_name='QR-код отсканирован'),
        ),
    ]
