# Generated by Django 5.1 on 2025-08-05 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_event_scanner_account_eventparticipant_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sign_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Плата за вступление'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)], verbose_name='Комиссия сервиса'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Стоимость'),
        ),
    ]
