# Generated by Django 5.1 on 2025-09-26 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_alter_event_sign_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='paid_by_organizer',
        ),
        migrations.RemoveField(
            model_name='event',
            name='scanner_account',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sign_price',
        ),
        migrations.RemoveField(
            model_name='eventparticipant',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='eventparticipant',
            name='qr_code_verified',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='commission_percent',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='price',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_will_pay',
            field=models.BooleanField(blank=True, null=True, verbose_name='Организатор оплатит встречу'),
        ),
        migrations.AddField(
            model_name='theme',
            name='organizer_price',
            field=models.PositiveIntegerField(default=5, verbose_name='Стоимость для организаторов'),
        ),
        migrations.AddField(
            model_name='theme',
            name='participant_price',
            field=models.PositiveIntegerField(default=1, verbose_name='Стоимость для участников'),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.theme', verbose_name='Тема'),
        ),
        migrations.DeleteModel(
            name='LegalEntity',
        ),
        migrations.DeleteModel(
            name='Verification',
        ),
    ]
