# Generated by Django 4.2.7 on 2024-07-31 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('period_type', models.CharField(choices=[('YEAR', 'Год'), ('MONTH', 'Месяц'), ('DAY', 'День')], max_length=8, verbose_name='Тип периода')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость, Р')),
                ('sort_value', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ('sort_value',),
            },
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='unlimited',
        ),
        migrations.AddField(
            model_name='wallet',
            name='unlimited_until',
            field=models.DateField(blank=True, help_text='Монеты не будут списываться за операции до установленной даты', null=True, verbose_name='Неограниченный до даты'),
        ),
    ]
