# Generated by Django 5.1 on 2025-02-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_coinsubscription_remove_wallet_unlimited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.PositiveIntegerField(default=100, verbose_name='1*, рублей'),
        ),
    ]
