# Generated by Django 5.1 on 2025-02-06 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_alter_exchangerate_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('SPEND', 'Расход'), ('REFUND', 'Возврат'), ('REPLENISHMENT', 'Пополнение')], max_length=16, verbose_name='Операция')),
                ('value', models.PositiveIntegerField(verbose_name='Количество')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='coins.wallet', verbose_name='Кошелек')),
            ],
            options={
                'verbose_name': 'операцию',
                'verbose_name_plural': 'История операций',
            },
        ),
    ]
